# Author: Arthur Cadore M. Barcella
# github: arthurcadore
# File: Main coposition file for sig-cloud application
# =======================================================
version: "3"
services:
# =======================================================
# Sig Cloud adapter application container: 
  sigcloud:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: sigCloud-Capacita
    volumes:
      - "./src/:/project"
      - "./auth:/root/.config/sig-cloud"
