# Use a imagem base
FROM eclipse-temurin:17-jdk-jammy

RUN echo "::::::::::::::::::::::::::: SIG CLOUD APPLICATION IN DOCKER  :::::::::::::::::::::::::::"
RUN echo "Author: Arthur Cadore M. B."
RUN echo "Github: arthurcadore"
# Defina o diretório de trabalho
WORKDIR /project

# Comando padrão para iniciar a aplicação
CMD ["java", "-jar", "eponadapter.jar"]
